# Generated by Django 3.2 on 2021-04-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='priority',
            new_name='members',
        ),
    ]
