# Generated by Django 3.2 on 2021-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_priority_todo_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='ldate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
