# Generated by Django 3.2 on 2021-04-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='cname',
        ),
    ]
