# Generated by Django 3.2 on 2021-04-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_name_contact_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=models.AutoField(primary_key=True)),
        ),
    ]
